### ISSUE TITLE
Accessing Refs

### ISSUE THREAD

**Issue by danistefanovic** [karlbright/react-stub-context#2]
Is there a way to access Refs of wrapped components?

```js
const WithStubbedContext = stubContext(MyComponent, { foo: FooStub });
const myComponent = TestUtils.renderIntoDocument(<WithStubbedContext  />);
TestUtils.Simulate.click(React.findDOMNode(myComponent.refs.myFancyButton));
```

**Comment by jarredwitt** [comment]
I was having this issue as well. After digging around in the index.js and the react docs I was able to get access to the wrapped element's refs after changing the following from: 

```
this._wrappedElement = React.createElement(BaseComponent, _extends({}, this.state, this.props)),
```
to
```
this._wrappedElement = React.createElement(BaseComponent, _extends({}, {ref: "wrappedElement"}, this.props)),
```

Once I made that change I was able to access all of the wrappedElement's methods and properties using:
```
let StubbedComponent = stubContext(Component, {context...});
StubbedComponent.refs.wrappedElement
```
I'm not really sure what the use is for this.state in the current implementation for createElement because it seems to be null all of the time for me - very little experience with this module so far. 

I also saw the getWrappedElement method but I was not able to get access to the refs using this method. I'm guessing that this may have something to do with holding on to items returned from render. Look at this page about refs for more info - [More About Refs](https://facebook.github.io/react/docs/more-about-refs.html).

At any rate, that's how I got it working and I can make a pull request as well if that's needed.

**Comment by karlbright** [comment]
Please feel free to PR if you have a good solution for this. I'm not entirely sure why refs are not accessible via `.refs` through stubbedComponentElement or wrappedElement. I may need to look in to how refs are handled a little more for this.

**Comment by cbrwizard** [comment]
Having this issue too. I guess that's another reason to have separate smart and dumb components

**Comment by karlbright** [comment]
@cbrwizard Absolutely the way to go. I'd recommend that over using this heavily for testing all the time :)

**Comment by sushantdhiman** [comment]
I am facing this issue as well, was this ever resolved ?
